# Generated by Django 4.2.3 on 2023-08-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_auctionlistings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='acitve',
            new_name='active',
        ),
    ]
