# Generated by Django 4.2.3 on 2023-09-01 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlistings_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.CharField(default='COMMENT', max_length=200),
        ),
        migrations.AddField(
            model_name='comments',
            name='thelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thelist', to='auctions.auctionlistings'),
        ),
    ]
