# Generated by Django 4.2.3 on 2023-09-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_bid_bids_thebid_alter_auctionlistings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='thebid',
            field=models.IntegerField(default=0),
        ),
    ]
